site_name: docs.saltbox.dev
site_url: https://docs.saltbox.dev/
site_author: salty
site_description: Saltbox is an Ansible-based solution for rapidly deploying a Docker containerized cloud media server.

repo_name: docs
repo_url: https://github.com/saltyorg/docs

edit_uri: edit/main/docs/

theme:
  name: material
  custom_dir: overrides
  features:
    - header.autohide
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - navigation.instant
    # - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

plugins:
  - search:
      lang: en

extra:
  generator: false
  social:
  - icon: fontawesome/solid/heart
    link: 'https://github.com/sponsors/saltydk'
    name: Donate
  - icon: fontawesome/brands/discord
    link: 'https://discord.gg/ugfKXpFND8'
    name: Discord
  - icon: fontawesome/brands/github
    link: 'https://github.com/saltyorg/Saltbox'
    name: GitHub

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.tilde
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Home: index.md
  - Saltbox:
      - Basics: saltbox/basics/basics.md
      - Prerequisites: saltbox/prerequisites/prerequisites.md
      - Install Types: saltbox/basics/install_types.md
      - Install: saltbox/install/install.md
      - After-Install: saltbox/install/after.md
      - Update: saltbox/basics/update.md
      - Accessing Apps: saltbox/basics/accessing_apps.md
      - Paths: saltbox/basics/paths.md
      - Inventory: saltbox/inventory/index.md
      - Backup/Restore:
        - Settings: saltbox/backup/settings.md
        - Backup: saltbox/backup/backup.md
        - Restore: saltbox/backup/restore.md
  - Community:
      - Basics: community/basics.md
      - Settings: community/settings.md
      - Index: community/index.md
      - Apps:
        - Downloading:
          - Torrents:
            - Deluge: community/apps/deluge.md
            - Delugex: community/apps/delugex.md
            - Qbittorrent: community/apps/qbittorrent.md
            - Qbittorrentx: community/apps/qbittorrentx.md
            - Rflood: community/apps/rflood.md
            - Rfloodx: community/apps/rfloodx.md
            - Transmission: community/apps/transmission.md
            - Transmissionx: community/apps/transmissionx.md
        - File Management:
          - Transfer: community/apps/transfer.md
        - Media Management:
          - ArrX: community/apps/arrx.md
          - Books:
            - readarr: community/apps/readarr.md
            - readarrx: community/apps/readarrx.md
          - Indexers:
            - prowlarr: community/apps/prowlarr.md
          - Metadata Management:
            - bazarr: community/apps/bazarr.md
            - bazarrx: community/apps/bazarrx.md
          - Movies:
            - radarrx: community/apps/radarrx.md
          - Music:
            - lidarrx: community/apps/lidarrx.md
          - TV:
            - sonarrx: community/apps/sonarrx.md
        - Media Servers and add-ons:
          - jellyfin: community/apps/jellyfin.md
          - Plex:
            - asshama: community/apps/asshama.md
            - tautullix: community/apps/tautullix.md
          - Requests:
            - ombi: community/apps/ombi.md
            - ombix: community/apps/ombix.md
            - petio: community/apps/petio.md
            - requestrr: community/apps/requestrr.md
            - requestrrx: community/apps/requestrrx.md
        - Utilities:
          - Docker:
            - dozzle: community/apps/dozzle.md
            - yacht: community/apps/yacht.md
          - Log Management:
            - goaccess: community/apps/goaccess.md
          - influxdb: community/apps/influxdb.md
          - System:
            - autoscan: community/apps/autoscan.md
            - btrfsmaintenance: community/apps/btrfsmaintenance.md
            - healthchecks: community/apps/healthchecks.md
            - hetzner_nfs: community/apps/hetzner_nfs.md
          - telegraf: community/apps/telegraf.md
          - Unpackerr: community/apps/unpackerr.md
          - uptime_kuma: community/apps/uptime_kuma.md
          - Visualization:
            - grafana: community/apps/grafana.md
            - varken: community/apps/varken.md
      - Guides:
        - General:
          - chazlarson Guides:
              - Can I run Saltbox on this server?: community/guides/chazguides/server.md
              - Did my Saltbox install succeed?: community/guides/chazguides/success.md
              - Plex Autoscan Mappings; how do they work?: community/guides/chazguides/pas-map.md
              - How do I mount a teamdrive?: community/guides/chazguides/teamdrive.md
              - I can't see my media!: community/guides/chazguides/no-media.md
              - Tip 44 Guide to Shared Drive/Service Account setup for Saltbox: community/guides/chazguides/tip44.md
              - I want some app to load at my base domain: community/guides/chazguides/base-domain.md
              - Why is my disk full?: community/guides/chazguides/disk-full.md
              - Installing Saltbox on a home server: community/guides/chazguides/home-server.md
        - Linux:
          - aliases: community/guides/aliases.md
        - Plex:
          - Tautulii Custom Scripts: community/guides/tautuliscripts.md
        - Downloading:
          - Hardlinking: community/guides/hardlinking.md
        - Migration:
          - cloudbox: community/guides/cloudbox.md
          - plexguide: community/guides/plexguide.md
        - Further Reading and Links:
          - Suggested Reading: community/guides/suggested_reading.md
          - Links: community/guides/links.md
  - Apps:
      - cloudplow: apps/cloudplow.md
      - emby: apps/emby.md
      - overseerr: apps/overseerr.md
      - plex: apps/plex.md
      - radarr: apps/radarr.md
      - sonarr: apps/sonarr.md
      - nzbget: apps/nzbget.md
      - nzbhydra2: apps/nzbhydra2.md
      - plex-autoscan: apps/plex-autoscan.md
      - portainer: apps/portainer.md
      - rutorrent: apps/rutorrent.md
      - sabnzbd: apps/sabnzbd.md
      - tautulli: apps/tautulli.md
      - lidarr: apps/lidarr.md
      - REPLACE IMAGES:
        - jackett: apps/jackett.md
      - NEED UPDATING:
        - organizr: apps/organizr.md
        - sstv: apps/sstv.md
  - FAQ:
      - System: faq/System.md
      - Cloud Storage: faq/Cloud Storage.md
      - CloudFlare: faq/Cloudflare.md
      - Cloudplow: faq/Cloudplow.md
      - Docker: faq/Docker.md
      - Install: faq/Install.md
      - Backup and Restore: faq/Backup and Restore.md
      - Rclone: faq/Rclone.md
      - Plex: faq/Plex.md
      - Plex-Autoscan: faq/Plex-Autoscan.md
      - ruTorrent: faq/ruTorrent.md
      - Misc: faq/Misc.md
  - Advanced:
      - Index: advanced/index.md
      - Adding Your Own Containers: advanced/your-own-containers.md
      - User crontab examples: advanced/user-crontab-examples.md
  - Reference:
      -Topics:
        - Prerequisites:
          - Server: reference/server.md
          - Domain Name: reference/domain.md
          - Cloud Storage: reference/cloud.md
          - Plex Account: reference/plex.md
          - Media Sources: reference/usenet-torrent.md
        - Google:
          - Google Project: reference/google-project-setup.md
          - Google Group: reference/google-group-setup.md
          - Google SDK: reference/google-gcloud-tools-install.md
          - Google Service Accounts: reference/google-service-accounts.md
          - Google Shared Drives: reference/google-shared-drives.md
        - Install:
          - Dependencies: reference/dependencies.md
          - Accounts and Settings: reference/accounts.md
          - Preinstall: reference/preinstall.md
          - Rclone: reference/rclone.md
          - Rclone [Manual]: reference/rclone-manual.md
          - Install: reference/install.md
        - Other:
          - Cloudplow Examples: reference/cloudplow.md
          - Customizing Plex Libraries: reference/customizing-plex-libs.md
          - Plex Auth Token: reference/plex_auth_token.md
          - Plex Autoscan Extras: reference/plex-autoscan-extras.md
          - Ports: reference/ports.md
          - Pushover: reference/pushover.md
          - Saltbox Tools: reference/saltbox-tools.md
          - Subdomains: reference/subdomain.md
          - Using Local Storage: reference/local-storage.md
  - Sandbox:
      - Basics: sandbox/basics.md
      - Settings: sandbox/settings.md
      - Index: sandbox/index.md
      - Apps:
        - General:
          - AdGuard Home: sandbox/apps/adguardhome.md
          - Nabarr: sandbox/apps/nabarr.md
          - Notifiarr: sandbox/apps/notifiarr.md
          - The Lounge: sandbox/apps/thelounge.md
          - Wrapperr: sandbox/apps/wrapperr.md
          - ZNC: sandbox/apps/znc.md
        - Content Management:
          - Wordpress: sandbox/apps/wordpress.md
        - Development:
          - Coder: sandbox/apps/coder.md
          - Gitea: sandbox/apps/gitea.md
        - Downloading:
          - AirDC++: sandbox/apps/airdcpp.md
          - Alltube: sandbox/apps/alltube.md
          - Archivebox: sandbox/apps/archivebox.md
          - Jdownloader2: sandbox/apps/jdownloader2.md
          - Medusa: sandbox/apps/medusa.md
          - Torrents:
            - Delugevpn: sandbox/apps/delugevpn.md
            - qBit Management: sandbox/apps/qbit_manage.md
        - File Management:
          - Filebot: sandbox/apps/filebot.md
          - Filebrowser: sandbox/apps/filebrowser.md
          - Filezilla: sandbox/apps/filezilla.md
          - Jirafeau: sandbox/apps/jirafeau.md
        - Landing Pages:
          - heimdall: sandbox/apps/heimdall.md
        - Media Management:
          - Books:
            - booksonic: sandbox/apps/booksonic.md
            - bookstack: sandbox/apps/bookstack.md
            - calibre: sandbox/apps/calibre.md
            - calibre_web: sandbox/apps/calibre_web.md
            - comicstreamer: sandbox/apps/comicstreamer.md
            - kavita: sandbox/apps/kavita.md
            - komga: sandbox/apps/komga.md
            - lazylibrarian: sandbox/apps/lazylibrarian.md
            - mylar3: sandbox/apps/mylar3.md
          # - Indexers:
          - Metadata Management:
            - alternatrr: sandbox/apps/alternatrr.md
            - alternatrrx: sandbox/apps/alternatrrx.md
            - comixed: sandbox/apps/comixed.md
            - MKVToolNix: sandbox/apps/mkvtoolnix.md
            - Plex Meta Manager: sandbox/apps/plex-meta-manager.md
            - unmanic: sandbox/apps/unmanic.md
          # - Movies:
          - Music:
            - airsonic: sandbox/apps/airsonic.md
            - beets: sandbox/apps/beets.md
            - funkwhale: sandbox/apps/funkwhale.md
            - deemix: sandbox/apps/deemix.md
            - navidrome: sandbox/apps/navidrome.md
          - TV:
            - xteve: sandbox/apps/xteve.md
        - Media Servers and add-ons:
          - Emby:
            - embystat: sandbox/apps/embystat.md
          - Plex:
            - Extended Personal Media Scanner: sandbox/apps/epms.md
            - goplaxt: sandbox/apps/goplaxt.md
            - kitana: sandbox/apps/kitana.md
            - Wrapperr: sandbox/apps/wrapperr.md
          # - Requests:
          - stash: sandbox/apps/stash.md
        - Nextcloud: sandbox/apps/nextcloud.md
        - Social:
          - gotify: sandbox/apps/gotify.md
          - moviematch: sandbox/apps/moviematch.md
        - Utilities:
          - Docker:
            - ouroboros: sandbox/apps/ouroboros.md
            - watchtower: sandbox/apps/watchtower.md
          - Networking:
            - kcptun_client: sandbox/apps/kcptun_client.md
            - kcptun_server: sandbox/apps/kcptun_server.md
          - flaresolverr: sandbox/apps/flaresolverr.md
          - Log Management:
            - logarr: sandbox/apps/logarr.md
            - monitorr: sandbox/apps/monitorr.md
          - guacamole: sandbox/apps/guacamole.md
          - handbrake: sandbox/apps/handbrake.md
          - speedtest: sandbox/apps/speedtest.md
          - sshwifty: sandbox/apps/sshwifty.md
          - System:
            - apprise: sandbox/apps/apprise.md
            - glances_web: sandbox/apps/glances_web.md
          - vaultwarden: sandbox/apps/vaultwarden.md
